name: quark-sign
on:
  # schedule:
    # - cron: 33 22 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run sign
        run: |
          python3 ./main.py
        env:
          COOKIE_QUARK1: ${{ secrets.COOKIE_QUARK1 }}
          COOKIE_QUARK2: ${{ secrets.COOKIE_QUARK2 }}
          COOKIE_QUARK3: ${{ secrets.COOKIE_QUARK3 }}
          BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
          BARK_ICON: ${{ secrets.BARK_ICON }}
